services:
  consul_standalone:
    image: hashicorp/consul:latest
    container_name: consul-server
    restart: always
    ports:
      - "${CONSUL_HTTP_PORT}:8500"           # Web UI & API
      - "${CONSUL_DNS_PORT}:8600/tcp"        # DNS (TCP)
      - "${CONSUL_DNS_PORT}:8600/udp"        # DNS (UDP)
      - "${CONSUL_SERVER_RPC_PORT}:8300"     # Server RPC
      - "${CONSUL_SERF_LAN_PORT}:8301"       # Serf LAN
      - "${CONSUL_SERF_LAN_PORT}:8301/udp"   # Serf LAN (UDP)
      - "${CONSUL_SERF_WAN_PORT}:8302"       # Serf WAN
      - "${CONSUL_SERF_WAN_PORT}:8302/udp"   # Serf WAN (UDP)
    volumes:
      - ./consul_standalone/data:/consul/data
      - ./consul_standalone/config:/consul/config
    env_file:
      - env/consul.env
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"