services:
  mysql:
    image: 'mysql:8.0.31'
    container_name: mysql
    privileged: true
    command: ["mysqld"]
    volumes:
      - ./mysql/data/:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - LANG=C.UTF-8
