services:
  # ─── Consul ───────────────────────────────────────────────────────────────
  consul_standalone:
    image: hashicorp/consul:latest
    container_name: consul-server
    restart: always
    ports:
      - "8500:8500"      # Web UI & API
      - "8600:8600/tcp"  # DNS (TCP)
      - "8600:8600/udp"  # DNS (UDP)
      - "8300:8300"      # Server RPC
      - "8301:8301"      # Serf LAN
      - "8301:8301/udp"  # Serf LAN (UDP)
      - "8302:8302"      # Serf WAN
      - "8302:8302/udp"  # Serf WAN (UDP)
    volumes:
      - ./data/consul_standalone/data:/consul/data
      - ./data/consul_standalone/config:/consul/config
    env_file:
      - env/consul.env
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"

  solr:
    image: solr:8.11.2
    ports:
      - "8983:8983"
    env_file:
      - env/solr.env
    depends_on:
      - zoo
    command: >
      bash -lc "
      solr zk mkroot -z zoo:2181 /ENGCD-search/cluster1 || true &&
      solr start -f -h 198.18.0.1"

  zoo:
    image: zookeeper:3.9
    ports:
      - "2182:2181"
    env_file:
      - env/zoo.env
