services:
  kafka:
    image: 'wurstmeister/kafka:2.13-2.8.1'
    networks:
      - docker-kit-network
    ports:
      - '${KAFKA_PORT}:9092'
    env_file:
      - env/kafka.env
    environment:
      # advertised listener 走域名，从根 .env 注入
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_HOSTNAME}:${KAFKA_PORT}
    volumes:
      - ./kafka/data:/kafka
    depends_on:
      - kafka_zk
  kafka_zk:
    image: wurstmeister/zookeeper
    networks:
      - docker-kit-network
    volumes:
      - ./kafka/zk_data:/data
    ports:
      - '${KAFKA_ZK_PORT}:2181'

networks:
  docker-kit-network:
    external: true