services:
  consul_standalone:
    image: hashicorp/consul:latest
    container_name: consul-server
    restart: always
    ports:
      - "8500:8500"      # Web UI & API
      - "8600:8600/tcp"  # DNS (TCP)
      - "8600:8600/udp"  # DNS (UDP)
      - "8300:8300"      # Server RPC
      - "8301:8301"      # Serf LAN
      - "8301:8301/udp"  # Serf LAN (UDP)
      - "8302:8302"      # Serf WAN
      - "8302:8302/udp"  # Serf WAN (UDP)
    volumes:
      - ./consul_standalone/data:/consul/data
      - ./consul_standalone/config:/consul/config
    env_file:
      - env/consul.env
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"