services:
  danmu-api:
    image: logvar/danmu-api:latest
    container_name: danmu-api
    ports:
      - "9321:9321"
    environment:
      - TOKEN=12345678  # 请将your_token_here 替换为实际的 Token 值 #不需要的话删除当前行
      - PLATFORM_ORDER=qiyi,bilibili1,imgo,youku,qq,tencent,renren,hanjutv
      - SOURCE_ORDER=360,vod,tencent,renren,hanjutv
      - YOUKU_CONCURRENCY=16
    restart: always
