server {
    listen 443 ssl;
    server_name _;

    include /etc/nginx/snippets/ssl.conf;

    # 允许上传大文件（Maven artifact）
    client_max_body_size 1g;

    location / {
        proxy_pass         http://vaultwarden:80;
        include            /etc/nginx/snippets/proxy-headers.conf;
    }
}

server {
    listen 80;
    server_name vault.zaqbest.com;
    return 301 https://$host$request_uri;
}
